---
apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapdrop
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapdrop
  template:
    metadata:
      labels:
        app: snapdrop
    spec:
      containers:
        - name: snapdrop
          image: linuxserver/snapdrop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http-snapdrop
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: snapdrop
  namespace: tools
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-snapdrop
      nodePort: 30180
  selector:
    app: snapdrop
  sessionAffinity: None
  type: LoadBalancer
---