apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.30.3
  share: /volume2/k8s_pv
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
